### ISSUE TITLE
job applications US bugs

### ISSUE THREAD

**Issue by sandys** [RedCarpetUp/lobsters#16]
1. i clicked shortlist by accident. please put a link saying "reset status". that will bring the status back to "applied" from wherever. obviously this will also trigger a auto comment and mail
2. oh god - please give me a link in an application "back to all applications". Right now it is "back to job" (which is good in itself), but I also need to go back to list of all applications for that job directly without going to the job itself.

**Comment by sidevesh** [comment]
ok...on it
