### ISSUE TITLE
plan out a feature for posting jobs and applying for them 

### ISSUE THREAD

**Issue by sandys** [RedCarpetUp/lobsters#4]
this is not like naukri . This is for startups to post their jobs and manage applications 

this is a lightweight version of something http://recruiterbox.com/

**Comment by sandys** [comment]
https://www.jazz.co/features/job-postings/

**Comment by sandys** [comment]
also read this - https://www.quora.com/What-is-the-best-applicant-tracking-system-for-new-and-growing-companies/answer/Hunter-Horsley

https://www.workable.com/

**Comment by sidevesh** [comment]
Let's have a seperate jobs section in the site:

![screenshot 8](https://cloud.githubusercontent.com/assets/17254413/16806673/14631a6e-4933-11e6-8328-2378b03f775b.png)

When a job is selected it should look something like this: 
Simple with all the relevant sections and an APPLY button:
![capture](https://cloud.githubusercontent.com/assets/17254413/16806802/a8873ce8-4933-11e6-86f4-ae81aa07ae72.PNG)

One someone clicks on APPLY he will fill out a form with all the relevant sections usually present in an application:
Name, email, Education, Work Experience, Projects, Links they want to post (e.g) github profile etc.

When the person who posted the job visits the applications section they can see the list of all applications, 
![job_page](https://cloud.githubusercontent.com/assets/17254413/16808223/41ab6dea-4939-11e6-9394-6910732936d1.png)

they can click on an application to see full details from where they can Shortlist or Reject them.
Then they can send email to those selected for further interaction ( interview etc ) informing them of their selection and for interaction.
![application_page](https://cloud.githubusercontent.com/assets/17254413/16808240/536c0512-4939-11e6-8d63-1412b93531d3.png)

Once a candidate is selected, the job posting can be removed by specifying resolution (candidate found or not, if yes who ) and clicking on CLOSE.

MODELS:
![untitlessd](https://cloud.githubusercontent.com/assets/17254413/16808723/4122d8ca-493b-11e6-8640-f0144bd91016.png)

**Comment by sandys** [comment]
sounds good. 

question - does applicant have to be a user ? If yes - then when a user creates a job, then he must be able to sign up. that will break the invitation flow. 
We can hack this - when a person wants to apply for a job, show him a page "request for invite" with email address field. Then the system generates an automatic invite and sends it to him. he has to sign up and then apply. I'm fine with this flow. 
thoughts ?

**Comment by sidevesh** [comment]
Yes...that would work...
